[package]
name = "ttrack"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.37"
clap = "4.5.4"
expanduser = "1.2.2"
eyre = "0.6.12"
rusqlite = { version = "0.31.0", features = ["bundled", "chrono"] }
serde = { version = "1.0.199", features = ["derive"] }
serde_json = "1.0.116"
